### ISSUE TITLE
kernel and signature on other partition than EFI & grub

### ISSUE THREAD

**Issue by davidhuwyler** [Wind-River/meta-secure-core#32]
Hi

I try to make secureboot work on our custom board.
My problem:
If the kernel & kernel signature are on an other partition than the one which contains grub / efi, the signature file is not found.
I guess the problem is, that the efi call mok2_verify_file expects things to be on the efi partition.
Is there a way to change this (set the search partition or something)?

Regards
Dave

**Comment by yizhao1** [comment]
Have you tried this patch https://github.com/Wind-River/meta-secure-core/blob/master/meta-efi-secure-boot/recipes-bsp/grub/grub-efi/grub-efi-support-passing-a-buffer-to-be-verified.patch ?

**Comment by davidhuwyler** [comment]
Yes this works! But the patch from SELoader is also needed to make it work.
The problem was: im on the kirkstone branch, which hasnt got those patches...
Thanks!
Dave
