### ISSUE TITLE
grub-efi password

### ISSUE THREAD

**Issue by Dvergatal** [Wind-River/meta-secure-core#40]
I'm sorry but I cannot find anywhere in the docs what is the password for grub - the only thing is this hashed password in password.inc... Can somebody tell it here? I suppose that docs needs an update as well.

**Comment by yizhao1** [comment]
The default password is root.  But we strongly recommend you to change the default password with grub-mkpasswd-pbkdf2 by yourself. I will update docs later. Thanks.

**Comment by Dvergatal** [comment]
Hi @yizhao1, thx for quick respond.

I know that it is needed to change the password:D but for the testing purposes I want to use the one provided by the official layer.
