### ISSUE TITLE
shim oe_runmake fails

### ISSUE THREAD

**Issue by AdrianDeWinter** [Wind-River/meta-secure-core#57]
I am encountering an issue using with UEFI secure boot without MOK secure boot.
When I set the SIGNING_MODEL to "user", the shim recipe fails to build with this error message:

`Error: file not found: /opt/yocto/build/tmp/work/corei7-64-poky-linux/shim/12+gitAUTOINC+5202f80c32-r0/vendor_dbx.esl`

Looking through the code, the vendor_dbx.esl file is only created if MOK_SB is active ([meta-signing-key/classes/user-key-store.bbclass:303](https://github.com/Wind-River/meta-secure-core/blob/master/meta-signing-key/classes/user-key-store.bbclass#L303)):
```
def create_mok_vendor_dbx(d):
    if d.getVar('MOK_SB', True) != '1' or d.getVar('SIGNING_MODEL', True) != 'user':
        return None
```

But the EXTRA_OEMAKE variable in the shim recipe is initialized like this([meta-efi-secure-boot/recipes-bsp/shim/shim_15.8.bb:41](https://github.com/Wind-River/meta-secure-core/blob/master/meta-efi-secure-boot/recipes-bsp/shim/shim_15.8.bb#L41)):
```
     ${@'VENDOR_CERT_FILE=${WORKDIR}/vendor_cert.cer' \
        if d.getVar('MOK_SB') == '1' else ''} \
     ${@'VENDOR_DBX_FILE=${WORKDIR}/vendor_dbx.esl' \
        if uks_signing_model(d) == 'user' else ''} \
```

From what i can see, the latter block should be guarded by MOK_SB==1 and SIGNING_MODEL=='user', not just MOK_SB.
I think a possible fix would this be as simple as:
```
     ${@'VENDOR_CERT_FILE=${WORKDIR}/vendor_cert.cer' \
        if d.getVar('MOK_SB') == '1' else ''} \
     ${@'VENDOR_DBX_FILE=${WORKDIR}/vendor_dbx.esl' \
        if d.getVar('MOK_SB') == '1' and uks_signing_model(d) == 'user' else ''} \
```

I originally ran into this on the kirkstone branch, but looking at the current master branch, the same issue seems to exist there.

If I'm operating under some massive misconception here please let me know, but I do think this is a bug. I'd would be willing to whip up a PR for each branch, if my understanding of this issue is indeed correct

**Comment by yizhao1** [comment]
I can confirm that this is a bug and your fix is correct. If you could submit a PR it would be much appreciated.

**Comment by AdrianDeWinter** [comment]
All right, thank you!
That was a very fast response :D

I have already set up a fork with the fix, would you like me submit it only against master and you backport it yourself, or against master, kirkstone and any others that have the bug?

**Comment by yizhao1** [comment]
> All right, thank you! That was a very fast response :D
> 
> I have already set up a fork with the fix, would you like me submit it only against master and you backport it yourself, or against master, kirkstone and any others that have the bug?

Only against master. I will backport it to other branches.

**Comment by AdrianDeWinter** [comment]
Alright, done :)
