### ISSUE TITLE
user-key-store.bbclass is missing import and mode for opening file

### ISSUE THREAD

**Issue by Dvergatal** [Wind-River/meta-secure-core#61]
When building with SIGNING_MODEL as user than in user-key-store.bbclass we are missing `import shutil` and `'rb'` mode for opening file.

**Comment by Dvergatal** [comment]
Yes I have already a fix for that and I have forgotten to mention that it is for the kikrstone release sorry for that...

**Comment by yizhao1** [comment]
Thanks. The issue also exits on master and scarthgap. I will merge it into these branches.
