### ISSUE TITLE
Kirkstone: Build fails at secure-core-minimal-image.bb:do_rootfs

### ISSUE THREAD

**Issue by AdrianDeWinter** [Wind-River/meta-secure-core#64]
I am trying to build the secure-core-minimal-image with only UEFI_SB and UEFI_SELOADER enabled.
The build fails at do-rootfs with this error:

```
Error: Transaction test error:
  file /boot/efi/EFI/BOOT/bootx64.efi conflicts between attempted installs of seloader-0.4.6+git0+8b90f76a8d-r0.corei7_64 and shim-12+git0+5202f80c32-r0.corei7_64
```

If I add MOK_SB, the build succeeds.

This is my configuration:
```
INIT_MANAGER = "systemd"
DISTRO_FEATURES_NATIVE:append = " systemd tpm tpm2 efi-secure-boot"
DISTRO_FEATURES:append = " systemd tpm tpm2 efi-secure-boot modsign"

EFI_PROVIDER = "grub-efi"

SIGNING_MODEL := "user"
require conf/distro/secure-boot/user-keys/keys.conf

DEBUG_FLAGS:forcevariable = ""
IMAGE_INSTALL:append = " kernel-image-bzimage"
GRUB_SIGN_VERIFY = "0"
UEFI_SB = "1"
UEFI_SELOADER = "1"
MOK_SB = "0"
```

- Is this a supported combination? The README mentions running SELoader without MOK secure boot, and, looking at the shim and seloader .bb files, i see that SELoader only installs it's .efi file as bootx64.efi if UEFI_SB is active and MOK_SB is not, which supports that assumption.
- shim on the other hand only checks UEFI_SB to see whether it should install signed or unsigned binaries, but always assumes it will be the bootx64.efi.

This looks like bug to me, but I'm not entirely certain as to what things should look like.
I'm guessing that either:
- SELoader is missing a condition for installing itself as bootx64.efi,
- or shim should not be built in the first place.

In the latter cased, I think the fix would look something like this:
[meta-efi-secure-boot/recipes-base/packagegroups/packagegroup-efi-secure-boot.bb](https://github.com/Wind-River/meta-secure-core/blob/kirkstone/meta-efi-secure-boot/recipes-base/packagegroups/packagegroup-efi-secure-boot.bb#L9):
```
SELOADER_PKG = "${@'seloader' if d.getVar('UEFI_SELOADER') == '1' else ''}"
SHIM_PKG = "${@'' if d.getVar('UEFI_SELOADER') == '1' and d.getVar('MOK_SB') != '1' else 'shim'}"
ALLOW_EMPTY:${PN} = "1"

pkgs = "\
    grub-efi \
    efitools \
    efibootmgr \
    mokutil \
    ${SELOADER_PKG} \
    ${SHIM_PKG} \
"
```
I patched my packagegroup-efi-secure-boot.bb like this and got a bootable image out of it.
I can't currently test this on scarthgap (our board vendor is being difficult), but the relevant code looks unchanged, so I'm guessing that branch is in the same boat.

**Comment by yizhao1** [comment]
Hi, Can you try the above patch ? Thanks.

**Comment by AdrianDeWinter** [comment]
I did, and it seems to fix the issue (as in, the error went away).

However, right now I am having a possibly unrelated issue, where only grubx64.efi and grub.conf are deployed to EFI/BOOT,
all other files are built and show up next to the image, but not in the boot partition.

Until I get that resolved, I can't be sure whether there are  any side effects from my suggested patch.
I will open a PR with it, I'm sure you have a quick test build you can run on it to see if it's safe

**Comment by AdrianDeWinter** [comment]
Nvm, I'm blind. I thought you meant my suggestion, I did not see that you linked a PR. I will test that now!
