### ISSUE TITLE
Why does meta-secure-core exclude UEFI Secure Boot for ARM?

### ISSUE THREAD

**Issue by jetm** [Wind-River/meta-secure-core#67]
Hi,

While adding UEFI Secure Boot to ARM in meta-arm layer, I saw many parts implemented in meta-secure-code that could be useful for ARM too, but those are excluded for ARM. Is there a particular reason(s) why ARM is excluded?

**Comment by yizhao1** [comment]
Hi, this original layer was created in 2017 which aimed Secure Boot on x86 platforms. At that time we had not considered UEFI boot on ARM. So we just excluded other architectures (including ARM) from the build. So far we have not tried to support UEFI boot on ARM with this layer. Of course, you can submit patches to enable ARM builds if needed.

**Comment by jetm** [comment]
Thank you. Let's see what I can do.
